"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var todoItem_1 = require("./models/todoItem");
var todoList_1 = require("./services/todoList");
var typeGuards_1 = require("./utils/typeGuards");
var todo1 = new todoItem_1.ToDoItem(1, "Vásárlás", new Date('2024-06-01'));
var todo2 = new todoItem_1.ToDoItem(2, "Edzés", new Date('2024.06.08'));
var todo3 = new todoItem_1.ToDoItem(3, "Takarítás", new Date('2024.05.18'));
var todo4 = new todoItem_1.ToDoItem(4, "Alvás", new Date('2024.11.11'));
var todo5 = new todoItem_1.ToDoItem(5, "Futás", new Date('2023.11.04'));
var todoList = new todoList_1.TodoList();
todoList.addItem(todo1);
todoList.addItem(todo2);
todoList.addItem(todo3);
todoList.addItem(todo4);
todoList.addItem(todo5);
console.log(todoList.listAllItems());
todoList.deleteItem(todo1);
console.log(todoList.listAllItems());
var meret = todoList.size;
console.log(meret);
var oneItem = todoList.listOneItem(todo3);
console.log(oneItem);
console.log(typeGuards_1.typeGuards.typeCheck(todo1));
